name: Build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        include:
          - build-name: 'Windows'
            platform: windows-latest
            arch: 'x64'
          - build-name: 'macOS'
            platform: macos-latest
            arch: 'arm64'
          - build-name: 'Ubuntu'
            platform: ubuntu-latest
            arch: 'x64'

    name: ${{ matrix.build-name }}

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install PyQt6 nsmblib PyInstaller
    - name: Build
      shell: bash
      run: PYQT_VERSION=PyQt6 python -OO build_release.py
    - name: Tar (macOS/Linux)
      if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      run: |
        cd distrib
        tar -czvf ../build-${{ matrix.platform }}.tar.gz ./*
        cd ..
    - name: Upload artifacts (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v7
      with:
        name: build-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.python-version }}
        path: distrib/*
    - name: Upload artifacts (macOS/Linux)
      if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      uses: actions/upload-artifact@v7
      with:
        name: build-${{ matrix.platform }}-${{ matrix.arch }}
        path: build-${{ matrix.platform }}.tar.gz
